version: "3.9"

services:
  nginx:
    container_name: ${DOCKER_APP_NAME}_nginx
    image: nginx
    tty: true
    ports:
      - ${DOCKER_APP_PORT}:80
    volumes:
      - ../backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - parsertagsnet

  backend:
    container_name: ${DOCKER_APP_NAME}_backend
    build:
      context: .
      dockerfile: docker/backend/php-fpm/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ../backend:/var/www
      - ./docker/backend/php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      PHP_IDE_CONFIG: "serverName=PhpParserTagsServerDocker"
    networks:
      - parsertagsnet

networks:
  parsertagsnet:
    driver: bridge
